{
 "title": "ATKafka",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(atkafka_handled_events,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Firehose Received Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(collection, action_name) (rate(atkafka_handled_events{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{collection}} ({{action_name}})"
    }
   ]
  },
  {
   "title": "Produced Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (rate(atkafka_produced_events{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status, cached, kind) (rate(atkafka_api_requests{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{kind}} cached={{cached}} status={{status}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(kind, status, cached) (rate(atkafka_plc_requests{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{kind}} cached={{cached}} status={{status}}"
    }
   ]
  },
  {
   "title": "Cache Sizes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atkafka_cache_size{instance=\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}